### ISSUE TITLE
Share your connection -> settings page

### ISSUE THREAD

**Issue by ignasbernotas** [mysteriumnetwork/dvpn-web#64]
https://projects.invisionapp.com/share/4BT9F7MZX2H#/screens/376803546

- Rename "Share your connection" title to "Settings page"
- Hide connection information section
- Remove inline form field buttons
- Rename "Start service" to "Save settings"
> Save settings should save the whole form.
- Replace Airdrop Wallet field text to:
> Enter the address of an ERC-20 compatible wallet. This is where you will get paid your ETH. Don’t have a wallet? Get it here.
- Replace header button "Provide VPN" to "Back to dashboard"

**Comment by chompomonim** [comment]
Not relevant anymore. We're working on new WebUI.
