### ISSUE TITLE
Settings page / Email field 

### ISSUE THREAD

**Issue by ignasbernotas** [mysteriumnetwork/dvpn-web#65]
https://projects.invisionapp.com/share/4BT9F7MZX2H#/screens/376803546

- Email field is mandatory if the Wallet field is completed and valid
- Email field is optional if the Wallet field is empty
- Show email confirmation status + link to confirm (we don't have this in the backend API yet, but let's have it in the UI)

**Comment by RenatBuga** [comment]
- [ ] Show the options for selecting the traffic type (All vs Whitelisted) as per screenshot
- [ ] E-mail field does not validate when the Wallet field is empty.
- [ ] Save button does not work when the Email field is valid, but Wallet is empty.
- [ ] Rename **Settings page** to **Settings** and **Save settings** to **Save**

**Comment by chompomonim** [comment]
Not relevant anymore. We're working on new WebUI.
