### ISSUE TITLE
Menu adjustments

### ISSUE THREAD

**Issue by ignasbernotas** [mysteriumnetwork/dvpn-web#66]
Remove the title of the menu - Settings

Point Terms & Conditions item to the page with terms (without the button Start service)

Remove Change password, About the app. 

Add mailto: bounty@mysterium.network in Send feedback.

Add the Settings item as first in the menu and point it to the Setting page.

**Comment by RenatBuga** [comment]
@vzinchenko06 
_Point Terms & Conditions item to the page with terms (without the button Start service)_ - here must be a new page with just terms without button Start service. Show the header bar with menu and button Back to Dashboard.

**Comment by RenatBuga** [comment]
Tested. Can be closed.
