### ISSUE TITLE
Enter button is disabled after an error

### ISSUE THREAD

**Issue by tadaskay** [mysteriumnetwork/dvpn-web#79]
If an error occurs during login, the Enter button stays in the disabled state. Keyboard enter key works though.

![Screenshot 2019-10-12 at 14 52 50](https://user-images.githubusercontent.com/4745368/66701042-1b945680-ed00-11e9-97bb-cf730d1c93b8.png)

**Comment by chompomonim** [comment]
We're working on new WebUI.
